Connect redux with API
haroldmud/new-bookstore pull request #3
Opened 2022-06-10 23:23 UTC by haroldmud

## In this branch I did the following :point_down: 
- Added redux-thunk to my project.
- Used [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) or [axios](https://axios-http.com/docs/intro) for making API calls.
- Fetched book list from Bookstore API on Books page load.
- Refactored my add book and remove book features to persist my changes in the server.

2022-06-10 23:48 UTC, Rustamxon7 requested changes
Hi @haroldmud  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_

![emojibest_com_AnimatedSticker](https://user-images.githubusercontent.com/69011963/172995573-7d2f291c-ffc6-47d8-bbe1-697b18445df3.gif)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-10 23:48 UTC, Rustamxon7 commented on src/redux/Books/Books.js
>  ];
- [ ] Please kindly remove the unused commented code 👍🏼

2022-06-10 23:48 UTC, Rustamxon7 commented on package.json
> +    "axios": "^0.27.2",
- [ ] [OPTIONAL] Please also add MIT.md license file 👋🏼

2022-06-11 06:37 UTC, OLIPLICHE approved these changes
Hi @haroldmud , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-11 10:39 UTC, merged